In [2]:
# creating a dataframe with pandas 

import pandas as pd 
import numpy as np 

d = { 'col1': [1,2,3,4,7], 'col2': [4,5,6,9,5], 'col3': [7,8,12,1,11]}

df = pd.DataFrame(data= d)

df

col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

In [ ]:
# counting the number of rows and columns

count_column = df.shape[1]      # here 1 represents the column

count_row = df.shape[0]         # here 0 represents the row

count_column

count_row

5

In [ ]:

# numpy data types 

arr = np.array([1,2,3,4,5])

print(arr.dtype)            # prints the dataype of the given array

arr_2 = np.array(['apple', 'banana', 'grapes'])

print(arr_2.dtype)          

int32
<U6


In [12]:
# creating arrays with defined data type 

defined_array = np.array([1,2,3,4], dtype= 'S')

print(defined_array.dtype)

|S1


In [ ]:
# values not being able to be converted 

err_array = np.array([1, 'apple', 500], dtype= 'i')

err_array.dtype         # throws an error cause we have defined the dtype of an array to be an integer and we have passed string.

ValueError: invalid literal for int() with base 10: 'apple'

In [ ]:
# coverting the datatype on existing array 

convert_array = np.array([1.1, 2.2, 3.3])

new_array = convert_array.astype('i')       # changes the float dtype to integer 

new_array.dtype

dtype('int32')

In [17]:
# numpy copy vs view 

# copy is the new array, any changes made to it does not change the original array

org_array = np.array([1,2,3,4,5])

cpy_array = org_array.copy()

org_array[0] = 100

org_array

cpy_array

array([1, 2, 3, 4, 5])

In [22]:
# view, any changes made to it will affect the orginal array 

org_array = np.array([1,2,3,4,5])

view_array = org_array.view()

org_array[0] = 100

org_array

view_array

array([100,   2,   3,   4,   5])

In [30]:
# checking if array owns the data 

arr = np.array([1,2,3,4,5])

x= arr.copy()
y= arr.view()

print(x.base)           # BASE returns none if the array owns the data.
print(y.base)

None
[1 2 3 4 5]


In [32]:
# numpy array shape 

arr = np.array([1,2,3,4], ndmin=5)

arr.shape

(1, 1, 1, 1, 4)

In [ ]:
# numpy array reshaping

# reshape from 1D to 2D 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_Arr = arr.reshape(4,3)      

new_Arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# reshape from 1D to 3D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_Array = arr.reshape(2,3,2)

new_Array

new_Array.base      # return the original array so it is a view.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
# unknown dimension

# Convert 1D array with 8 elements to 3D array with 2x2 elements

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_Arr = arr.reshape(2,2,-1)

new_Arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# flattening the arrays: meaning conveting multi dimensional array into 1D array

arr = np.array([[1,2,3],[4,5,6]])

new_arr = arr.reshape(-1)       # -1 converts the 2D array into 1D array in this case.

new_arr

array([1, 2, 3, 4, 5, 6])