In [1]:
import numpy as np 

In [5]:
# vectorization-- converting the iterative statements into a vector based operation

x = [1,2,3,4,5]

y = [1,2,3,4,5]

z = np.add(x,y)     # here add is the unfunc, using this we can add without iterating the elements of array

print(z)

[ 2  4  6  8 10]


In [7]:
# creating our own unfunc

def add(x,y):
    return x+y 

myadd = np.frompyfunc(add, 2, 1)        # func, inputs, outputs

print(myadd([1,2,3,4], [1,2,3,4]))


[2 4 6 8]


In [8]:
# checking if a func is a unfunc

type(np.add)

numpy.ufunc

In [12]:
# simple arithematic 

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

new_array_add = np.add(arr1, arr2)

new_array_add

array([30, 32, 34, 36, 38, 40])

In [15]:
new_array_subtract = np.subtract(arr2, arr1)

new_array_subtract

array([10, 10, 10, 10, 10, 10])

In [16]:
new_array_multiply = np.multiply(arr1, arr2)

new_array_multiply

array([200, 231, 264, 299, 336, 375])

In [17]:
new_array_division = np.divide(arr1, arr2)

new_array_division

array([0.5       , 0.52380952, 0.54545455, 0.56521739, 0.58333333,
       0.6       ])

In [18]:
new_Array_power = np.power(arr1, arr2)

new_Array_power

array([ 1661992960,   602408795,           0,  1487897765,  1090519040,
       -1144744561])

In [19]:
new_Array_mod = np.mod(arr1, arr2)

new_Array_mod

array([10, 11, 12, 13, 14, 15])

In [20]:
arr3 = [-10,-20,-30]

new_array_absolute = np.absolute(arr3)

new_array_absolute

array([10, 20, 30])

In [ ]:
# summations 

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

new_array_sum = np.sum([arr1, arr2])        # this gives the sum of that array

new_array_sum

12

In [ ]:
# summations over an axis 

new_array_axis = np.sum([arr1, arr2], axis= 1)      # perform sum over an axis

new_array_axis

array([6, 6])

In [ ]:
# cumulative sum

new_arr_cumsum = np.cumsum(arr1)        # gives the cumulative sum

new_arr_cumsum

array([1, 3, 6])

In [ ]:
# numpy products 

new_array_prod = np.prod(arr1)      # 1*2*3

new_array_prod

6

In [ ]:
new_arr_prods = np.prod([arr1, arr2])       # 1*2*3*1*2*3 meaning multiplies the number of both the array

new_arr_prods

36

In [ ]:
# cumulative product 

new_array_cumprod = np.cumprod(arr1)        # 1, 1*2, 1*2*3

new_array_cumprod

array([1, 2, 6])

In [29]:
# numpy trigonometric functions

x = np.sin(np.pi/2)

x

1.0

In [32]:
# converting degrees into radians 

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

x

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [33]:
# radian to degrees

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

x



array([ 90., 180., 270., 360.])

In [ ]:
# finding angles 

x = np.arcsin(1.0)      # returns the radian values 

y = np.rad2deg(x)

y

90.0

In [40]:
# angles of each value in array 

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

y = np.rad2deg(x)

y

array([ 90.        , -90.        ,   5.73917048])

In [ ]:
# hypotenuses 

base = 4 
perpendicular = 3 

height = np.hypot(base, perpendicular)       #calculates the height using pythagoras theorem

height

5.0

In [44]:
# hyperbolic functions 

hyperbolic_fun = np.sinh(np.pi/2)

change_func = np.rad2deg(hyperbolic_fun)

change_func

131.85471450029715

In [ ]:
# finding angles 

x = np.arcsinh(1.0)

change_deg = np.rad2deg(x)

change_deg

50.49898671052622

In [ ]:
# rounding decimals 

# using trunc

arr = np.trunc([-3.1666, 3.6667])       # rounds to the closest zero.

print(arr)

[-3.  3.]


In [50]:
# using fix 

arr = np.fix([-3.1666, 3.667])

arr

array([-3.,  3.])

In [ ]:
# using around 

arr = np.around(3.1666, 2)      # increases the preceding decimal by 1 if >=5 else do nothing.

arr

3.17

In [ ]:
# using floor 

arr = np.floor([-3.1666, 3.1999])       # rounds off decimal to nearest lowest integer.

arr

array([-4.,  3.])

In [ ]:
# using ceil 

arr = np.ceil([3.1667, -3.1667])        # rounds off decuimal to nearest upper integer.

arr

array([ 4., -3.])